// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA34UjjmJhJBWLyW8ZgZvULsxkjkeZGq9E',
    appId: '1:403757706301:web:832225e7d3e1e899f44e54',
    messagingSenderId: '403757706301',
    projectId: 'chat-app-57d62',
    authDomain: 'chat-app-57d62.firebaseapp.com',
    storageBucket: 'chat-app-57d62.firebasestorage.app',
    measurementId: 'G-JB7XPJ3EM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYYy8zgEg_boIc5DRKhoejjUCMsA3fKjs',
    appId: '1:403757706301:android:85d336593dbb561bf44e54',
    messagingSenderId: '403757706301',
    projectId: 'chat-app-57d62',
    storageBucket: 'chat-app-57d62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7bgWR-EzrSzCpWQFvUjaAaIHBNY95tlM',
    appId: '1:403757706301:ios:9a2650f68ef0aa81f44e54',
    messagingSenderId: '403757706301',
    projectId: 'chat-app-57d62',
    storageBucket: 'chat-app-57d62.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7bgWR-EzrSzCpWQFvUjaAaIHBNY95tlM',
    appId: '1:403757706301:ios:9a2650f68ef0aa81f44e54',
    messagingSenderId: '403757706301',
    projectId: 'chat-app-57d62',
    storageBucket: 'chat-app-57d62.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA34UjjmJhJBWLyW8ZgZvULsxkjkeZGq9E',
    appId: '1:403757706301:web:0565e9a37fd5b1d6f44e54',
    messagingSenderId: '403757706301',
    projectId: 'chat-app-57d62',
    authDomain: 'chat-app-57d62.firebaseapp.com',
    storageBucket: 'chat-app-57d62.firebasestorage.app',
    measurementId: 'G-X1FKS0LTCW',
  );
}
